import { config } from '@fohte/eslint-config'

export default config(
  {
    ignores: ['vendor/**', 'vendor-dist/**', 'dist/**'],
  },
  {
    typescript: { typeChecked: true },
    errorHandling: {},
  },
  {
    files: ['src/vault-fetcher.ts'],
    rules: {
      // The vendor bundle is generated by scripts/build-vendor.mjs and is
      // intentionally referenced by a relative path.
      'no-restricted-imports': 'off',
    },
  },
  {
    files: ['src/**/*.test.ts'],
    rules: {
      // Test stubs implement async interfaces and intentionally have no awaits.
      '@typescript-eslint/require-await': 'off',
    },
  },
)
